#global values can be overwritten by assigning after global import <<: *global
global: &global
  secure_scheme: true
  default_browser: :firefox
  default_timeout: 30

theinternet:
  default_site: https://the-internet.herokuapp.com
  capybara_default_driver: :selenium_chrome
  <<: *global
  default_timeout: 4
  default_browser: :chrome
  username: tomsmith
  password: SuperSecretPassword!
  headless: false
